services:
  bromley-bin-reminder:
    build: .
    container_name: bin-reminder
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped
    environment:
      URL: ${URL}
      EMAIL_ADDRESSES: ${EMAIL_ADDRESSES}
      REMINDER_TIME: ${REMINDER_TIME}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_SERVER: ${SMTP_SERVER}
      SMTP_PORT: ${SMTP_PORT}
