services:
  bromley-bin-reminder:
    container_name: bin-reminder
    image: mholubinka1/bromley-bin-reminder:latest
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - /home/pi/.config/bin-reminder:/config
    restart: unless-stopped
