services:
  bromley-bin-reminder:
    container_name: bin-reminder
    image: mholubinka1/bromley-bin-reminder:latest
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      URL: ${URL}
      EMAIL_ADDRESSES: ${EMAIL_ADDRESSES}
      REMINDER_TIME: ${REMINDER_TIME}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_SERVER: ${SMTP_SERVER}
      SMTP_PORT: ${SMTP_PORT}
    restart: unless-stopped
